name: news_app
description: TDD News App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: 2.0.0
  http: 0.13.1
  cached_network_image: 3.0.0-nullsafety
  cupertino_icons: ^1.0.0
  data_connection_checker: 0.3.4
  dartz: 0.10.0-nullsafety.1
  flutter_bloc: 7.0.0
  get_it: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.12.2

  json_annotation: 4.0.1
  auto_route_generator: 1.0.2
  freezed: 0.14.1+2
  mockito: 5.0.3
  bloc_test: 8.0.0
  json_serializable: 4.1.0

  lint: 1.5.3
  # derry: ^1.2.1

scripts: derry.yaml

flutter:

  
  uses-material-design: true


